/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADatanetworkconnectDataop extends PDataop
{
    private PDatanetworkconnect _datanetworkconnect_;

    public ADatanetworkconnectDataop()
    {
        // Constructor
    }

    public ADatanetworkconnectDataop(
        @SuppressWarnings("hiding") PDatanetworkconnect _datanetworkconnect_)
    {
        // Constructor
        setDatanetworkconnect(_datanetworkconnect_);

    }

    @Override
    public Object clone()
    {
        return new ADatanetworkconnectDataop(
            cloneNode(this._datanetworkconnect_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADatanetworkconnectDataop(this);
    }

    public PDatanetworkconnect getDatanetworkconnect()
    {
        return this._datanetworkconnect_;
    }

    public void setDatanetworkconnect(PDatanetworkconnect node)
    {
        if(this._datanetworkconnect_ != null)
        {
            this._datanetworkconnect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._datanetworkconnect_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._datanetworkconnect_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._datanetworkconnect_ == child)
        {
            this._datanetworkconnect_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._datanetworkconnect_ == oldChild)
        {
            setDatanetworkconnect((PDatanetworkconnect) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
