/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADatabaseList extends PDatabaseList
{
    private TDatabaselistToken _databaselistToken_;

    public ADatabaseList()
    {
        // Constructor
    }

    public ADatabaseList(
        @SuppressWarnings("hiding") TDatabaselistToken _databaselistToken_)
    {
        // Constructor
        setDatabaselistToken(_databaselistToken_);

    }

    @Override
    public Object clone()
    {
        return new ADatabaseList(
            cloneNode(this._databaselistToken_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADatabaseList(this);
    }

    public TDatabaselistToken getDatabaselistToken()
    {
        return this._databaselistToken_;
    }

    public void setDatabaselistToken(TDatabaselistToken node)
    {
        if(this._databaselistToken_ != null)
        {
            this._databaselistToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._databaselistToken_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._databaselistToken_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._databaselistToken_ == child)
        {
            this._databaselistToken_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._databaselistToken_ == oldChild)
        {
            setDatabaselistToken((TDatabaselistToken) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
