/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADatanetworkconnect extends PDatanetworkconnect
{
    private TDatanetworkconnectToken _datanetworkconnectToken_;
    private TLPar _lPar_;
    private PWordOrNum _tablename_;
    private TRPar _rPar_;

    public ADatanetworkconnect()
    {
        // Constructor
    }

    public ADatanetworkconnect(
        @SuppressWarnings("hiding") TDatanetworkconnectToken _datanetworkconnectToken_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PWordOrNum _tablename_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setDatanetworkconnectToken(_datanetworkconnectToken_);

        setLPar(_lPar_);

        setTablename(_tablename_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ADatanetworkconnect(
            cloneNode(this._datanetworkconnectToken_),
            cloneNode(this._lPar_),
            cloneNode(this._tablename_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADatanetworkconnect(this);
    }

    public TDatanetworkconnectToken getDatanetworkconnectToken()
    {
        return this._datanetworkconnectToken_;
    }

    public void setDatanetworkconnectToken(TDatanetworkconnectToken node)
    {
        if(this._datanetworkconnectToken_ != null)
        {
            this._datanetworkconnectToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._datanetworkconnectToken_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PWordOrNum getTablename()
    {
        return this._tablename_;
    }

    public void setTablename(PWordOrNum node)
    {
        if(this._tablename_ != null)
        {
            this._tablename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tablename_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._datanetworkconnectToken_)
            + toString(this._lPar_)
            + toString(this._tablename_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._datanetworkconnectToken_ == child)
        {
            this._datanetworkconnectToken_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._tablename_ == child)
        {
            this._tablename_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._datanetworkconnectToken_ == oldChild)
        {
            setDatanetworkconnectToken((TDatanetworkconnectToken) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._tablename_ == oldChild)
        {
            setTablename((PWordOrNum) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
