/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADataconnectdb extends PDataconnectdb
{
    private TDataconnectdbToken _dataconnectdbToken_;
    private TLPar _lPar_;
    private PWordOrNum _wordOrNum_;
    private TRPar _rPar_;

    public ADataconnectdb()
    {
        // Constructor
    }

    public ADataconnectdb(
        @SuppressWarnings("hiding") TDataconnectdbToken _dataconnectdbToken_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PWordOrNum _wordOrNum_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setDataconnectdbToken(_dataconnectdbToken_);

        setLPar(_lPar_);

        setWordOrNum(_wordOrNum_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ADataconnectdb(
            cloneNode(this._dataconnectdbToken_),
            cloneNode(this._lPar_),
            cloneNode(this._wordOrNum_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADataconnectdb(this);
    }

    public TDataconnectdbToken getDataconnectdbToken()
    {
        return this._dataconnectdbToken_;
    }

    public void setDataconnectdbToken(TDataconnectdbToken node)
    {
        if(this._dataconnectdbToken_ != null)
        {
            this._dataconnectdbToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dataconnectdbToken_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PWordOrNum getWordOrNum()
    {
        return this._wordOrNum_;
    }

    public void setWordOrNum(PWordOrNum node)
    {
        if(this._wordOrNum_ != null)
        {
            this._wordOrNum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._wordOrNum_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dataconnectdbToken_)
            + toString(this._lPar_)
            + toString(this._wordOrNum_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dataconnectdbToken_ == child)
        {
            this._dataconnectdbToken_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._wordOrNum_ == child)
        {
            this._wordOrNum_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dataconnectdbToken_ == oldChild)
        {
            setDataconnectdbToken((TDataconnectdbToken) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._wordOrNum_ == oldChild)
        {
            setWordOrNum((PWordOrNum) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
