/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class APanelVizPanelop extends PPanelop
{
    private PPanelViz _panelViz_;

    public APanelVizPanelop()
    {
        // Constructor
    }

    public APanelVizPanelop(
        @SuppressWarnings("hiding") PPanelViz _panelViz_)
    {
        // Constructor
        setPanelViz(_panelViz_);

    }

    @Override
    public Object clone()
    {
        return new APanelVizPanelop(
            cloneNode(this._panelViz_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPanelVizPanelop(this);
    }

    public PPanelViz getPanelViz()
    {
        return this._panelViz_;
    }

    public void setPanelViz(PPanelViz node)
    {
        if(this._panelViz_ != null)
        {
            this._panelViz_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._panelViz_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._panelViz_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._panelViz_ == child)
        {
            this._panelViz_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._panelViz_ == oldChild)
        {
            setPanelViz((PPanelViz) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
