/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class APanelHandlePanelop extends PPanelop
{
    private PPanelHandle _panelHandle_;

    public APanelHandlePanelop()
    {
        // Constructor
    }

    public APanelHandlePanelop(
        @SuppressWarnings("hiding") PPanelHandle _panelHandle_)
    {
        // Constructor
        setPanelHandle(_panelHandle_);

    }

    @Override
    public Object clone()
    {
        return new APanelHandlePanelop(
            cloneNode(this._panelHandle_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPanelHandlePanelop(this);
    }

    public PPanelHandle getPanelHandle()
    {
        return this._panelHandle_;
    }

    public void setPanelHandle(PPanelHandle node)
    {
        if(this._panelHandle_ != null)
        {
            this._panelHandle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._panelHandle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._panelHandle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._panelHandle_ == child)
        {
            this._panelHandle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._panelHandle_ == oldChild)
        {
            setPanelHandle((PPanelHandle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
