/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class APanelClonePanelop extends PPanelop
{
    private PPanelClone _panelClone_;

    public APanelClonePanelop()
    {
        // Constructor
    }

    public APanelClonePanelop(
        @SuppressWarnings("hiding") PPanelClone _panelClone_)
    {
        // Constructor
        setPanelClone(_panelClone_);

    }

    @Override
    public Object clone()
    {
        return new APanelClonePanelop(
            cloneNode(this._panelClone_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPanelClonePanelop(this);
    }

    public PPanelClone getPanelClone()
    {
        return this._panelClone_;
    }

    public void setPanelClone(PPanelClone node)
    {
        if(this._panelClone_ != null)
        {
            this._panelClone_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._panelClone_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._panelClone_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._panelClone_ == child)
        {
            this._panelClone_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._panelClone_ == oldChild)
        {
            setPanelClone((PPanelClone) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
