/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ARemColumn extends PRemColumn
{
    private TColremove _colremove_;
    private TLPar _lPar_;
    private PColDef _newcol_;
    private final LinkedList<PColGroup> _colGroup_ = new LinkedList<PColGroup>();
    private TRPar _rPar_;

    public ARemColumn()
    {
        // Constructor
    }

    public ARemColumn(
        @SuppressWarnings("hiding") TColremove _colremove_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PColDef _newcol_,
        @SuppressWarnings("hiding") List<?> _colGroup_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setColremove(_colremove_);

        setLPar(_lPar_);

        setNewcol(_newcol_);

        setColGroup(_colGroup_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ARemColumn(
            cloneNode(this._colremove_),
            cloneNode(this._lPar_),
            cloneNode(this._newcol_),
            cloneList(this._colGroup_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARemColumn(this);
    }

    public TColremove getColremove()
    {
        return this._colremove_;
    }

    public void setColremove(TColremove node)
    {
        if(this._colremove_ != null)
        {
            this._colremove_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colremove_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PColDef getNewcol()
    {
        return this._newcol_;
    }

    public void setNewcol(PColDef node)
    {
        if(this._newcol_ != null)
        {
            this._newcol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newcol_ = node;
    }

    public LinkedList<PColGroup> getColGroup()
    {
        return this._colGroup_;
    }

    public void setColGroup(List<?> list)
    {
        for(PColGroup e : this._colGroup_)
        {
            e.parent(null);
        }
        this._colGroup_.clear();

        for(Object obj_e : list)
        {
            PColGroup e = (PColGroup) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._colGroup_.add(e);
        }
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colremove_)
            + toString(this._lPar_)
            + toString(this._newcol_)
            + toString(this._colGroup_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colremove_ == child)
        {
            this._colremove_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._newcol_ == child)
        {
            this._newcol_ = null;
            return;
        }

        if(this._colGroup_.remove(child))
        {
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colremove_ == oldChild)
        {
            setColremove((TColremove) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._newcol_ == oldChild)
        {
            setNewcol((PColDef) newChild);
            return;
        }

        for(ListIterator<PColGroup> i = this._colGroup_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PColGroup) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
