/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASelectorGroup extends PSelectorGroup
{
    private TComma _comma_;
    private PSelectorTerm _selectorTerm_;

    public ASelectorGroup()
    {
        // Constructor
    }

    public ASelectorGroup(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PSelectorTerm _selectorTerm_)
    {
        // Constructor
        setComma(_comma_);

        setSelectorTerm(_selectorTerm_);

    }

    @Override
    public Object clone()
    {
        return new ASelectorGroup(
            cloneNode(this._comma_),
            cloneNode(this._selectorTerm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelectorGroup(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PSelectorTerm getSelectorTerm()
    {
        return this._selectorTerm_;
    }

    public void setSelectorTerm(PSelectorTerm node)
    {
        if(this._selectorTerm_ != null)
        {
            this._selectorTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._selectorTerm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._selectorTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._selectorTerm_ == child)
        {
            this._selectorTerm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._selectorTerm_ == oldChild)
        {
            setSelectorTerm((PSelectorTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
