/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASelectorTerm extends PSelectorTerm
{
    private TVizType _vizType_;
    private PTerm _term_;

    public ASelectorTerm()
    {
        // Constructor
    }

    public ASelectorTerm(
        @SuppressWarnings("hiding") TVizType _vizType_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setVizType(_vizType_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new ASelectorTerm(
            cloneNode(this._vizType_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelectorTerm(this);
    }

    public TVizType getVizType()
    {
        return this._vizType_;
    }

    public void setVizType(TVizType node)
    {
        if(this._vizType_ != null)
        {
            this._vizType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vizType_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vizType_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vizType_ == child)
        {
            this._vizType_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vizType_ == oldChild)
        {
            setVizType((TVizType) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
