/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class AUnfiltercolColop extends PColop
{
    private PUnfilterColumn _unfilterColumn_;

    public AUnfiltercolColop()
    {
        // Constructor
    }

    public AUnfiltercolColop(
        @SuppressWarnings("hiding") PUnfilterColumn _unfilterColumn_)
    {
        // Constructor
        setUnfilterColumn(_unfilterColumn_);

    }

    @Override
    public Object clone()
    {
        return new AUnfiltercolColop(
            cloneNode(this._unfilterColumn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnfiltercolColop(this);
    }

    public PUnfilterColumn getUnfilterColumn()
    {
        return this._unfilterColumn_;
    }

    public void setUnfilterColumn(PUnfilterColumn node)
    {
        if(this._unfilterColumn_ != null)
        {
            this._unfilterColumn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unfilterColumn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unfilterColumn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unfilterColumn_ == child)
        {
            this._unfilterColumn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unfilterColumn_ == oldChild)
        {
            setUnfilterColumn((PUnfilterColumn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
