/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVizCommentVizop extends PVizop
{
    private PVizComment _vizComment_;

    public AVizCommentVizop()
    {
        // Constructor
    }

    public AVizCommentVizop(
        @SuppressWarnings("hiding") PVizComment _vizComment_)
    {
        // Constructor
        setVizComment(_vizComment_);

    }

    @Override
    public Object clone()
    {
        return new AVizCommentVizop(
            cloneNode(this._vizComment_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVizCommentVizop(this);
    }

    public PVizComment getVizComment()
    {
        return this._vizComment_;
    }

    public void setVizComment(PVizComment node)
    {
        if(this._vizComment_ != null)
        {
            this._vizComment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vizComment_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vizComment_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vizComment_ == child)
        {
            this._vizComment_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vizComment_ == oldChild)
        {
            setVizComment((PVizComment) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
