/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDatabaselistToken extends Token
{
    public TDatabaselistToken()
    {
        super.setText("database.list");
    }

    public TDatabaselistToken(int line, int pos)
    {
        super.setText("database.list");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDatabaselistToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDatabaselistToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDatabaselistToken text.");
    }
}
