/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDataimporttoken extends Token
{
    public TDataimporttoken()
    {
        super.setText("data.import");
    }

    public TDataimporttoken(int line, int pos)
    {
        super.setText("data.import");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDataimporttoken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDataimporttoken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDataimporttoken text.");
    }
}
