/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDatabaseconnectedconceptsToken extends Token
{
    public TDatabaseconnectedconceptsToken()
    {
        super.setText("database.getConnectedConcepts");
    }

    public TDatabaseconnectedconceptsToken(int line, int pos)
    {
        super.setText("database.getConnectedConcepts");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDatabaseconnectedconceptsToken(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDatabaseconnectedconceptsToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDatabaseconnectedconceptsToken text.");
    }
}
