/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.node;

import prerna.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class THelpCommand extends Token
{
    public THelpCommand()
    {
        super.setText("help");
    }

    public THelpCommand(int line, int pos)
    {
        super.setText("help");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THelpCommand(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHelpCommand(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THelpCommand text.");
    }
}
