/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.*;

@SuppressWarnings("nls")
public final class AComplexOrComparisonExpr extends PComparisonExpr
{
    private PComparisonGroup _comparisonGroup_;
    private TOrComparator _orComparator_;
    private PComparisonExpr _comparisonExpr_;

    public AComplexOrComparisonExpr()
    {
        // Constructor
    }

    public AComplexOrComparisonExpr(
        @SuppressWarnings("hiding") PComparisonGroup _comparisonGroup_,
        @SuppressWarnings("hiding") TOrComparator _orComparator_,
        @SuppressWarnings("hiding") PComparisonExpr _comparisonExpr_)
    {
        // Constructor
        setComparisonGroup(_comparisonGroup_);

        setOrComparator(_orComparator_);

        setComparisonExpr(_comparisonExpr_);

    }

    @Override
    public Object clone()
    {
        return new AComplexOrComparisonExpr(
            cloneNode(this._comparisonGroup_),
            cloneNode(this._orComparator_),
            cloneNode(this._comparisonExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComplexOrComparisonExpr(this);
    }

    public PComparisonGroup getComparisonGroup()
    {
        return this._comparisonGroup_;
    }

    public void setComparisonGroup(PComparisonGroup node)
    {
        if(this._comparisonGroup_ != null)
        {
            this._comparisonGroup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparisonGroup_ = node;
    }

    public TOrComparator getOrComparator()
    {
        return this._orComparator_;
    }

    public void setOrComparator(TOrComparator node)
    {
        if(this._orComparator_ != null)
        {
            this._orComparator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orComparator_ = node;
    }

    public PComparisonExpr getComparisonExpr()
    {
        return this._comparisonExpr_;
    }

    public void setComparisonExpr(PComparisonExpr node)
    {
        if(this._comparisonExpr_ != null)
        {
            this._comparisonExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparisonExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comparisonGroup_)
            + toString(this._orComparator_)
            + toString(this._comparisonExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comparisonGroup_ == child)
        {
            this._comparisonGroup_ = null;
            return;
        }

        if(this._orComparator_ == child)
        {
            this._orComparator_ = null;
            return;
        }

        if(this._comparisonExpr_ == child)
        {
            this._comparisonExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comparisonGroup_ == oldChild)
        {
            setComparisonGroup((PComparisonGroup) newChild);
            return;
        }

        if(this._orComparator_ == oldChild)
        {
            setOrComparator((TOrComparator) newChild);
            return;
        }

        if(this._comparisonExpr_ == oldChild)
        {
            setComparisonExpr((PComparisonExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
