/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.Analysis;

@SuppressWarnings("nls")
public final class AExprColDef extends PColDef
{
    private PMasterExpr _masterExpr_;

    public AExprColDef()
    {
        // Constructor
    }

    public AExprColDef(
        @SuppressWarnings("hiding") PMasterExpr _masterExpr_)
    {
        // Constructor
        setMasterExpr(_masterExpr_);

    }

    @Override
    public Object clone()
    {
        return new AExprColDef(
            cloneNode(this._masterExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprColDef(this);
    }

    public PMasterExpr getMasterExpr()
    {
        return this._masterExpr_;
    }

    public void setMasterExpr(PMasterExpr node)
    {
        if(this._masterExpr_ != null)
        {
            this._masterExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._masterExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._masterExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._masterExpr_ == child)
        {
            this._masterExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._masterExpr_ == oldChild)
        {
            setMasterExpr((PMasterExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
