/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.*;

@SuppressWarnings("nls")
public final class AFrameopColDef extends PColDef
{
    private PFrameop _frameop_;

    public AFrameopColDef()
    {
        // Constructor
    }

    public AFrameopColDef(
        @SuppressWarnings("hiding") PFrameop _frameop_)
    {
        // Constructor
        setFrameop(_frameop_);

    }

    @Override
    public Object clone()
    {
        return new AFrameopColDef(
            cloneNode(this._frameop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFrameopColDef(this);
    }

    public PFrameop getFrameop()
    {
        return this._frameop_;
    }

    public void setFrameop(PFrameop node)
    {
        if(this._frameop_ != null)
        {
            this._frameop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._frameop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._frameop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._frameop_ == child)
        {
            this._frameop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._frameop_ == oldChild)
        {
            setFrameop((PFrameop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
