/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.Analysis;

@SuppressWarnings("nls")
public final class AMapNegNum extends PMapNegNum
{
    private TMinus _minus_;
    private PDecimal _decimal_;

    public AMapNegNum()
    {
        // Constructor
    }

    public AMapNegNum(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PDecimal _decimal_)
    {
        // Constructor
        setMinus(_minus_);

        setDecimal(_decimal_);

    }

    @Override
    public Object clone()
    {
        return new AMapNegNum(
            cloneNode(this._minus_),
            cloneNode(this._decimal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMapNegNum(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PDecimal getDecimal()
    {
        return this._decimal_;
    }

    public void setDecimal(PDecimal node)
    {
        if(this._decimal_ != null)
        {
            this._decimal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decimal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._decimal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._decimal_ == child)
        {
            this._decimal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._decimal_ == oldChild)
        {
            setDecimal((PDecimal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
