/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANounOpInput extends POpInput
{
    private PNoun _noun_;

    public ANounOpInput()
    {
        // Constructor
    }

    public ANounOpInput(
        @SuppressWarnings("hiding") PNoun _noun_)
    {
        // Constructor
        setNoun(_noun_);

    }

    @Override
    public Object clone()
    {
        return new ANounOpInput(
            cloneNode(this._noun_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANounOpInput(this);
    }

    public PNoun getNoun()
    {
        return this._noun_;
    }

    public void setNoun(PNoun node)
    {
        if(this._noun_ != null)
        {
            this._noun_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._noun_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._noun_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._noun_ == child)
        {
            this._noun_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._noun_ == oldChild)
        {
            setNoun((PNoun) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
