/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.*;

@SuppressWarnings("nls")
public final class ANumberOrStringTerm extends PTerm
{
    private PNumberOrString _numberOrString_;

    public ANumberOrStringTerm()
    {
        // Constructor
    }

    public ANumberOrStringTerm(
        @SuppressWarnings("hiding") PNumberOrString _numberOrString_)
    {
        // Constructor
        setNumberOrString(_numberOrString_);

    }

    @Override
    public Object clone()
    {
        return new ANumberOrStringTerm(
            cloneNode(this._numberOrString_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumberOrStringTerm(this);
    }

    public PNumberOrString getNumberOrString()
    {
        return this._numberOrString_;
    }

    public void setNumberOrString(PNumberOrString node)
    {
        if(this._numberOrString_ != null)
        {
            this._numberOrString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numberOrString_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numberOrString_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numberOrString_ == child)
        {
            this._numberOrString_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numberOrString_ == oldChild)
        {
            setNumberOrString((PNumberOrString) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
