/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.*;

@SuppressWarnings("nls")
public final class AOtherscript extends POtherscript
{
    private TPipe _pipe_;
    private PMasterExpr _masterExpr_;

    public AOtherscript()
    {
        // Constructor
    }

    public AOtherscript(
        @SuppressWarnings("hiding") TPipe _pipe_,
        @SuppressWarnings("hiding") PMasterExpr _masterExpr_)
    {
        // Constructor
        setPipe(_pipe_);

        setMasterExpr(_masterExpr_);

    }

    @Override
    public Object clone()
    {
        return new AOtherscript(
            cloneNode(this._pipe_),
            cloneNode(this._masterExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtherscript(this);
    }

    public TPipe getPipe()
    {
        return this._pipe_;
    }

    public void setPipe(TPipe node)
    {
        if(this._pipe_ != null)
        {
            this._pipe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pipe_ = node;
    }

    public PMasterExpr getMasterExpr()
    {
        return this._masterExpr_;
    }

    public void setMasterExpr(PMasterExpr node)
    {
        if(this._masterExpr_ != null)
        {
            this._masterExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._masterExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pipe_)
            + toString(this._masterExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pipe_ == child)
        {
            this._pipe_ = null;
            return;
        }

        if(this._masterExpr_ == child)
        {
            this._masterExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pipe_ == oldChild)
        {
            setPipe((TPipe) newChild);
            return;
        }

        if(this._masterExpr_ == oldChild)
        {
            setMasterExpr((PMasterExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
