/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.*;

@SuppressWarnings("nls")
public final class ARcol extends PRcol
{
    private TFrameprefix _frameprefix_;
    private TNumber _number_;

    public ARcol()
    {
        // Constructor
    }

    public ARcol(
        @SuppressWarnings("hiding") TFrameprefix _frameprefix_,
        @SuppressWarnings("hiding") TNumber _number_)
    {
        // Constructor
        setFrameprefix(_frameprefix_);

        setNumber(_number_);

    }

    @Override
    public Object clone()
    {
        return new ARcol(
            cloneNode(this._frameprefix_),
            cloneNode(this._number_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARcol(this);
    }

    public TFrameprefix getFrameprefix()
    {
        return this._frameprefix_;
    }

    public void setFrameprefix(TFrameprefix node)
    {
        if(this._frameprefix_ != null)
        {
            this._frameprefix_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._frameprefix_ = node;
    }

    public TNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(TNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._frameprefix_)
            + toString(this._number_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._frameprefix_ == child)
        {
            this._frameprefix_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._frameprefix_ == oldChild)
        {
            setFrameprefix((TFrameprefix) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((TNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
