/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.*;

@SuppressWarnings("nls")
public final class AScriptOperationOrVar extends POperationOrVar
{
    private PScript _script_;

    public AScriptOperationOrVar()
    {
        // Constructor
    }

    public AScriptOperationOrVar(
        @SuppressWarnings("hiding") PScript _script_)
    {
        // Constructor
        setScript(_script_);

    }

    @Override
    public Object clone()
    {
        return new AScriptOperationOrVar(
            cloneNode(this._script_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScriptOperationOrVar(this);
    }

    public PScript getScript()
    {
        return this._script_;
    }

    public void setScript(PScript node)
    {
        if(this._script_ != null)
        {
            this._script_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._script_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._script_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._script_ == child)
        {
            this._script_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._script_ == oldChild)
        {
            setScript((PScript) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
