/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc2.node;

import prerna.sablecc2.analysis.Analysis;

@SuppressWarnings("nls")
public final class TProjectid extends Token
{
    public TProjectid()
    {
        super.setText("p=");
    }

    public TProjectid(int line, int pos)
    {
        super.setText("p=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProjectid(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProjectid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProjectid text.");
    }
}
