#Properties
role_app		f9b656cc-06e7-4cce-bae8-b5f92075b6da
visn_app		f9b656cc-06e7-4cce-bae8-b5f92075b6da
station_app	f9b656cc-06e7-4cce-bae8-b5f92075b6da
#role_app		34257176-6e68-43ce-b5e5-bfcb0b4cd43a
#visn_app		34257176-6e68-43ce-b5e5-bfcb0b4cd43a
#station_app		34257176-6e68-43ce-b5e5-bfcb0b4cd43a
#purchase_settings_app	fcb46dea-6b06-43b0-bd78-6f1a4e3869c6
#email_preferences_app	83ce0cc4-7c48-4db7-b26b-88ef723026d7
vha_app		fe5e2c23-59e6-42ae-939d-b2ca9699f38c
#vha_app			3831cb1a-4496-46fe-8763-8044a00c04a7

catalogAttachmentsDir
doAttachmentsDir
counterfeitsAttachmentsDir
poAttachmentsDir

#Is Email Setup
#email_enabled true
#email_template_folder_path C:/workspace/vha-supply/emailTemplates/
#ncrt_link http://localhost:8080/va-supplychain/#!/
#request_status_link http://localhost:8080/va-supplychain/#!/demand-status/
#nc_request_status_link http://localhost:8080/va-supplychain/#!/non-catalog-status/
#request_approval_link http://localhost:8080/va-supplychain/#!/demand-approval/
#purchase_order_status_link http://localhost:8080/va-supplychain/#!/shipment-status/
#email_preferences_link http://localhost:8080/va-supplychain/#!/email-preferences/
#distribution_status_link http://localhost:8080/va-supplychain/#!/push-distribution-planning/
#distribution_plan_approval_link http://localhost:8080/va-supplychain/#!/distribution-plan-approval/
#covid_resource_link https://vaww.pclo.infoshare.va.gov/PCLO/MMStrategicPlan/PEO/COVID19/SitePages/Home.aspx
#ncrt_support_mailbox mailto:VACONCRTSupport@VA.gov
