/*******************************************************************************
 * Copyright 2015 Defense Health Agency (DHA)
 *
 * If your use of this software does not include any GPLv2 components:
 * 	Licensed under the Apache License, Version 2.0 (the "License");
 * 	you may not use this file except in compliance with the License.
 * 	You may obtain a copy of the License at
 *
 * 	  http://www.apache.org/licenses/LICENSE-2.0
 *
 * 	Unless required by applicable law or agreed to in writing, software
 * 	distributed under the License is distributed on an "AS IS" BASIS,
 * 	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * 	See the License for the specific language governing permissions and
 * 	limitations under the License.
 * ----------------------------------------------------------------------------
 * If your use of this software includes any GPLv2 components:
 * 	This program is free software; you can redistribute it and/or
 * 	modify it under the terms of the GNU General Public License
 * 	as published by the Free Software Foundation; either version 2
 * 	of the License, or (at your option) any later version.
 *
 * 	This program is distributed in the hope that it will be useful,
 * 	but WITHOUT ANY WARRANTY; without even the implied warranty of
 * 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * 	GNU General Public License for more details.
 *******************************************************************************/
package prerna.reactor.agent.sandbox;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import org.apache.commons.exec.CommandLine;
import org.apache.commons.exec.DefaultExecutor;
import org.apache.commons.exec.ExecuteWatchdog;
import org.apache.commons.exec.PumpStreamHandler;
import org.apache.commons.io.input.NullInputStream;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import prerna.util.Constants;

/**
 * Executes a one-shot shell command inside a {@link SandboxPolicy}-enforced subprocess,
 * reusing the same {@link SandboxLauncherRegistry} dispatch as the long-running agent harnesses.
 *
 * <p>Platform behaviour:
 * <ul>
 *   <li><b>Linux</b>: Landlock LSM via child JVM ({@link LandlockLauncher}) — ~500 ms overhead per call</li>
 *   <li><b>macOS</b>: {@code sandbox-exec} Seatbelt ({@link SandboxExecLauncher}) — ~20–50 ms per call</li>
 *   <li><b>Other / backend unavailable</b>: returns {@code null}; caller falls back to
 *       Layer-1 navigation confinement only</li>
 * </ul>
 *
 * <p>Linux/chroot note: Landlock restricts writes to the room folder only. Reads are
 * permitted across the chroot root (same access the chroot already provides) because
 * Landlock's allowlist model requires explicit READ_DIR grants on each ancestor directory
 * of the room folder path for kernel path traversal to succeed. The chroot already allows
 * this read access, so there is no security regression relative to the pre-Landlock state.
 * The meaningful gain is that writes outside the room folder are blocked at the kernel level.
 *
 * <p>macOS/no-chroot note: The SBPL profile generated by {@link SandboxExecLauncher} uses
 * {@code (allow file-read-metadata)} globally for traversal, then restricts content reads
 * and all writes precisely to the room folder. This is a tighter restriction than the
 * Linux/chroot case.
 */
public final class CmdSandboxLauncher {

	private static final Logger classLogger = LogManager.getLogger(CmdSandboxLauncher.class);

	private static final int COMMAND_TIMEOUT_SECONDS = 30;

	private CmdSandboxLauncher() {
	}

	/**
	 * Builds a {@link SandboxPolicy} for a room-session command execution.
	 *
	 * <p><b>macOS</b>: Uses the blocklist model — global {@code (allow file-read-data)}
	 * with targeted {@code deny} rules for sensitive directories.  Reason: macOS SBPL
	 * requires the broad read rule to be present for {@code file-write*} rules to
	 * take effect; removing it (the allowlist/strictReads approach) causes all writes
	 * to silently fail.  Security is enforced by blocking {@code /private/etc},
	 * {@code /Users} (outside the room), credential stores, and the SEMOSS home tree.
	 * The room folder is explicitly carved out as RW via a more-specific allow rule
	 * that overrides the {@code /Users} deny.
	 *
	 * <p><b>Linux</b>: Landlock is inherently allowlist-only, so explicit RO paths are
	 * added for the shell runtime.  For chroot sessions, the chroot root and every
	 * ancestor of {@code roomFolder} are also added as RO (Landlock path-traversal).
	 *
	 * @param roomFolder the room's working directory (system absolute path)
	 * @param chrootPath the user's chroot root, or {@code null} if chroot is not active
	 * @return policy ready to pass to {@link #execute}
	 */
	public static SandboxPolicy buildRoomCommandPolicy(String roomFolder, String chrootPath) {
		boolean useChrootWrapping = Platform.current() == Platform.LINUX
				&& chrootPath != null && !chrootPath.trim().isEmpty();

		// macOS sandbox-exec checks policy against the real (symlink-resolved) path.
		// Resolve roomFolder so the policy entry matches what the kernel sees after cd.
		String resolvedRoom = roomFolder;
		try {
			resolvedRoom = Paths.get(roomFolder).toRealPath().toString();
		} catch (IOException | SecurityException ignored) {
			// path not yet created or no access — use as-is; policy may be imprecise
		}

		SandboxPolicyBuilder b = SandboxPolicy.builder()
				.withEnforcement(AgentSandboxConfig.resolveEnforcement())
				.withLoopbackNetwork(false)
				.withReadWrite(resolvedRoom);
		// If roomFolder was a symlink, also allow the symlink path itself
		if (!resolvedRoom.equals(roomFolder)) {
			b.withReadWrite(roomFolder);
		}

		Platform platform = Platform.current();
		if (platform == Platform.LINUX) {
			// Landlock: explicit RO allowlist required (no global read rule).
			b.withRead("/bin");
			b.withRead("/usr/bin");
			b.withRead("/usr/lib");
			b.withRead("/usr/lib64");
			b.withRead("/lib");
			b.withRead("/lib64");
			b.withRead("/etc/ssl");
			b.withRead(System.getProperty("java.home"));
			if (useChrootWrapping) {
				// fakechroot needs to traverse the chroot root for path mapping
				b.withRead(chrootPath);
				// Landlock requires READ_DIR on every ancestor of roomFolder for traversal
				Path ancestor = Paths.get(roomFolder).getParent();
				while (ancestor != null && ancestor.getNameCount() > 0) {
					b.withRead(ancestor.toString());
					ancestor = ancestor.getParent();
				}
			}
		} else if (platform == Platform.MACOS) {
			// macOS blocklist model: global file-read-data + targeted deny rules.
			// Deny /private/etc broadly; carve out TLS certs via a more-specific allow.
			b.withBlock("/private/etc");
			b.withRead("/private/etc/ssl");

			// Deny all user home directories; the room carve-out above re-allows the room.
			b.withBlock("/Users");
			b.withBlock("/home");

			// Deny the SEMOSS home tree to prevent reading other projects/configs.
			String semossBase = prerna.util.Utility.getBaseFolder();
			if (semossBase != null && !semossBase.trim().isEmpty()) {
				try { b.withBlock(semossBase); } catch (IllegalArgumentException ignored) {}
			}

			// Deny credential stores (belt-and-suspenders in case they live outside /Users).
			for (String cred : AgentSandboxConfig.defaultSensitiveBlockList()) {
				try { b.withBlock(cred); } catch (IllegalArgumentException ignored) {}
			}

			// Allow temp directories for scratch space.
			b.withReadWrite("/private/tmp");
			b.withReadWrite("/var/folders");
			String javaHome = System.getProperty("java.home");
			if (javaHome != null && !javaHome.trim().isEmpty()) {
				b.withRead(javaHome);
			}
		}

		return b.build();
	}

	/**
	 * Runs {@code command} in a sandbox restricted to {@code policy}.
	 *
	 * <p>The effective shell invocation is:
	 * <pre>
	 *   cd '{workingDir}' &amp;&amp; {command}
	 * </pre>
	 * wrapped in {@code fakechroot fakeroot chroot} when {@code chrootPath} is non-null
	 * (Linux), or directly via {@code /bin/bash} otherwise (macOS dev).
	 *
	 * @param policy     pre-built policy (from {@link #buildRoomCommandPolicy})
	 * @param workingDir the directory to cd into before running (system absolute path)
	 * @param command    shell command string to execute
	 * @param chrootPath the user's chroot root, or {@code null} if chroot is not active
	 * @return {@code String[2]} — {@code [0]="true"/"false"}, {@code [1]=output};
	 *         or {@code null} if no sandbox backend is available (caller should fall back)
	 */
	public static String[] execute(SandboxPolicy policy, String workingDir,
			String command, String chrootPath) {
		SandboxLauncher launcher;
		try {
			launcher = SandboxLauncherRegistry.get();
		} catch (SandboxUnavailableException e) {
			classLogger.warn("No sandbox backend available for this platform; "
					+ "falling back to Layer-1 navigation confinement only: {}", e.getMessage());
			return null;
		}

		String escapedDir = workingDir.replace("'", "'\"'\"'");
		String shellCmd = "cd '" + escapedDir + "' && " + command;
		String   targetBinary;
		String[] targetArgs;

		boolean useChrootWrapping = Platform.current() == Platform.LINUX
				&& chrootPath != null && !chrootPath.trim().isEmpty();
		if (useChrootWrapping) {
			// Linux / chroot: wrap in fakechroot → fakeroot → chroot → bash
			targetBinary = "/usr/bin/fakechroot";
			targetArgs = new String[] {
					"fakeroot", "chroot", "--userspec=1001:1001", chrootPath,
					"/bin/bash", "-c", shellCmd
			};
		} else {
			// macOS (sandbox-exec handles confinement) or no-chroot
			targetBinary = "/bin/bash";
			targetArgs = new String[] { "-c", shellCmd };
		}

		SandboxLaunchPlan plan;
		try {
			plan = launcher.plan(policy, targetBinary, targetArgs);
		} catch (Exception e) {
			classLogger.error("Failed to build sandbox launch plan: {}", e.getMessage(), e);
			return null;
		}

		return runSandboxed(plan, targetArgs);
	}

	/**
	 * Executes the plan, collecting stdout+stderr into a {@code String[2]} result.
	 * The argv sent to the OS is: {@code [plan.cliPath, ...plan.cliArgs, ...targetArgs]}.
	 */
	private static String[] runSandboxed(SandboxLaunchPlan plan, String[] targetArgs) {
		String[] foutput = new String[2];

		// argv[0] = wrapper script; plan.cliArgs is always empty for both launchers,
		// but we respect it for forward-compatibility. targetArgs follow.
		CommandLine cmdLine = new CommandLine(plan.getCliPath());
		for (String arg : plan.getCliArgs()) {
			cmdLine.addArgument(arg, false);
		}
		for (String arg : targetArgs) {
			cmdLine.addArgument(arg, false);
		}

		// Merge current environment with launcher additions/removals
		Map<String, String> env = new HashMap<>(System.getenv());
		env.putAll(plan.getEnvironmentAdditions());
		plan.getEnvironmentRemovals().forEach(env::remove);

		ExecuteWatchdog watchdog = ExecuteWatchdog.builder()
				.setTimeout(Duration.ofSeconds(COMMAND_TIMEOUT_SECONDS))
				.get();
		DefaultExecutor executor = DefaultExecutor.builder().get();
		executor.setWatchdog(watchdog);

		try (ByteArrayOutputStream stdout = new ByteArrayOutputStream();
				ByteArrayOutputStream stderr = new ByteArrayOutputStream()) {

			executor.setStreamHandler(
					new PumpStreamHandler(stdout, stderr, NullInputStream.nullInputStream()));

			boolean success = true;
			try {
				executor.execute(cmdLine, env);
			} catch (Exception ex) {
				success = false;
				classLogger.debug("Sandboxed command exited non-zero: {}", ex.getMessage());
			}

			String out = (stdout.toString() + stderr.toString())
					.trim().replace("\\", "/");

			foutput[0] = String.valueOf(success);
			foutput[1] = out.isEmpty()
					? (success ? "Command executed successfully" : "Command failed with no output")
					: out;

		} catch (IOException e) {
			classLogger.error(Constants.STACKTRACE, e);
			foutput[0] = "false";
			foutput[1] = "IO Exception: " + e.getMessage();
		}

		return foutput;
	}
}
