handlers=java.util.logging.ConsoleHandler
.handlers=java.util.logging.ConsoleHandler
.level=INFO
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=org.apache.juli.OneLineFormatter
org.apache.catalina.startup.VersionLoggerListener.level=WARNING
