package prerna.sablecc2.om;

public enum PkslOperationTypes {

	// JOB INFORMATION
	JOB,
	JOB_DATA,
	JOB_METADATA,
	
	// FRAME INFORMATION
	FRAME,
	FRAME_DATA_CHANGE,
	FRAME_HEADERS,
	
	// PANEL OPERATIONS
	PANEL,
	PANEL_OPEN,
	PANEL_CLOSE,
	PANEL_ORNAMENT,
	PANEL_HEADER,
	PANEL_CLONE,
	
	// META DATA INFORMATION	
	CONNECTED_CONCEPTS,
	DATABASE_LIST,
	DATABASE_METAMODEL,
	DATABASE_CONCEPTS,
	DATABASE_CONCEPT_PROPERTIES,
	
	// INSIGHT INFORMATION
	RUN_SAVED_INSIGHT_DATA,
	NEW_INSIGHT_GENERATED,

	// SOME KIND OF OPERATION THAT WE WANT TO OUTPUT
	OPERATION
}
