#docker build . -t quay.io/semoss/docker:cuda12.5.1

# ARG BASE_REGISTRY=quay.io
# ARG BASE_IMAGE=semoss/docker-tomcat
# ARG BASE_TAG=cuda12.2

ARG BASE_REGISTRY=docker.io
ARG BASE_IMAGE=nvidia/cuda
ARG BASE_TAG=12.5.1-runtime-ubuntu22.04

# ARG R_HOME=/usr/lib/R
# ARG R_LIBS_SITE=/usr/local/lib/R/site-library
# ARG RSTUDIO_PANDOC=/usr/lib/R/pandoc-2.17.1.1/bin
ARG JAVA_HOME=/usr/lib/jvm/zulu8
ARG TOMCAT_HOME=/opt/apache-tomcat-9.0.102
ARG MAVEN_HOME=/opt/apache-maven-3.8.5

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS base
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS mavenpuller

# ARG JAVA_HOME=/usr/lib/jvm/zulu8
# ENV JAVA_HOME=${JAVA_HOME}

# From JAVA/tomcat
ARG JAVA_HOME=/usr/lib/jvm/zulu8
ENV JAVA_HOME=${JAVA_HOME}

ARG TOMCAT_VERSION=9.0.102
ENV TOMCAT_VERSION=${TOMCAT_VERSION}

ARG TOMCAT_HOME=/opt/apache-tomcat-${TOMCAT_VERSION}
ENV TOMCAT_HOME=${TOMCAT_HOME}

ARG MAVEN_HOME=/opt/apache-maven-3.8.5
ENV MAVEN_HOME=${MAVEN_HOME}

ENV PATH=$PATH:$MAVEN_HOME/bin:$TOMCAT_HOME/bin:$JAVA_HOME/bin

# Get tomcat, maven and java from another image called tomcat-builder
COPY --from=quay.io/semoss/tomcat-builder:9.0.102 /opt /opt
COPY --from=quay.io/semoss/tomcat-builder:9.0.102 /usr/lib/jvm/zulu8 /usr/lib/jvm/zulu8
COPY --from=quay.io/semoss/tomcat-builder:9.0.102 /opt/apache-maven-3.8.5/bin /opt/apache-maven-3.8.5/bin

# First install all required packages and set up directories
RUN apt-get update -y \
	&& apt-get install -y curl lsof git wget\
	&& mkdir /opt/semosshome \
	&& cd /opt && git clone https://github.com/SEMOSS/semoss-artifacts \
	&& chmod 777 /opt/semoss-artifacts/artifacts/scripts/*.sh \
	&& /opt/semoss-artifacts/artifacts/scripts/update_latest_dev.sh \
	&& chmod 777 /opt/semosshome/config/Chromedriver/* \
    && sed -i "s/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar,/g" $TOMCAT_HOME/conf/catalina.properties;


RUN useradd -u 1001 -r -g 0 -d ${HOME} -s /bin/bash         \
    -c "Default Application User" default &&                \
    chown -R 1001:0 ${HOME}

RUN mkdir /opt/chroot

RUN chown -R 1001:0 /opt

FROM  base AS intermediate

LABEL maintainer="semoss@semoss.org"

# From JAVA/tomcat
ARG JAVA_HOME=/usr/lib/jvm/zulu8
ENV JAVA_HOME=${JAVA_HOME}
ARG TOMCAT_VERSION=9.0.102
ARG TOMCAT_HOME=/opt/apache-tomcat-9.0.102   #NOTE: hardocoding tomcat version for now
ENV TOMCAT_HOME=${TOMCAT_HOME}

COPY --from=quay.io/semoss/tomcat-builder:9.0.102 /opt /opt
COPY --from=quay.io/semoss/tomcat-builder:9.0.102 /usr/lib/jvm/zulu8 /usr/lib/jvm/zulu8


# FROM mavenpuller as m-intermediate

LABEL maintainer="semoss@semoss.org"

ENV PATH=$PATH:/opt/semoss-artifacts/artifacts/scripts

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH

# RUN wget https://downloads.rclone.org/v1.60.0/rclone-v1.60.0-linux-amd64.deb \
#         && dpkg -i rclone-v1.60.0-linux-amd64.deb \
#         && apt-get install -f \
#         && rm rclone-v1.60.0-linux-amd64.deb \
#         && chmod 777 /usr/bin/rclone \
#         && mkdir $TOMCAT_HOME/webapps/Monolith \
#         && mkdir $TOMCAT_HOME/webapps/SemossWeb \
#         && cp $JAVA_HOME/lib/tools.jar $TOMCAT_HOME/lib \
#         && sed -i "s/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar,/g" $TOMCAT_HOME/conf/catalina.properties

# RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
#         && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list \
#         && apt-get update \
#         && apt-get install -y google-chrome-stable

COPY --from=mavenpuller /opt/semosshome /opt/semosshome
COPY --from=mavenpuller $TOMCAT_HOME/webapps/Monolith $TOMCAT_HOME/webapps/Monolith
COPY --from=mavenpuller $TOMCAT_HOME/webapps/SemossWeb $TOMCAT_HOME/webapps/SemossWeb
COPY --from=mavenpuller /opt/semoss-artifacts/ver.txt /opt/semoss-artifacts/ver.txt


# Get python from python-builder
COPY --from=python-builder:v1 /usr/lib/python /usr/lib/python

FROM scratch AS final

COPY --from=intermediate / /

# Add verification immediately after COPY
RUN ls -la /opt/apache-tomcat-9.0.102/webapps/Monolith/ \
    && ls -la /opt/apache-tomcat-9.0.102/webapps/SemossWeb/ \
    && echo "Files in final stage"

# ARG R_HOME
# ARG R_LIBS_SITE
# ARG RSTUDIO_PANDOC
ARG JAVA_HOME
ARG TOMCAT_HOME
ARG MAVEN_HOME

# ENV R_HOME=$R_HOME
# ENV R_LIBS_SITE=$R_LIBS_SITE
# ENV RSTUDIO_PANDOC=$RSTUDIO_PANDOC
ENV JAVA_HOME=$JAVA_HOME
ENV TOMCAT_HOME=$TOMCAT_HOME
ENV MAVEN_HOME=$MAVEN_HOME
ENV PATH=$PATH:$MAVEN_HOME/bin:$TOMCAT_HOME/bin:$JAVA_HOME/bin

WORKDIR /opt/semoss-artifacts/artifacts/scripts
CMD ["sh", "-c", "ls -la /opt/apache-tomcat-9.0.102/webapps/ && echo 'Starting Tomcat...' && . /opt/set_env.env && exec $TOMCAT_HOME/bin/catalina.sh run"]

# Add verification for critical directories
# RUN [ -d "$TOMCAT_HOME" ] && \
#     [ -d "$JAVA_HOME" ] && \
#     [ -d "/usr/lib/python" ]