# Base image arguments
ARG BASE_REGISTRY=registry.access.redhat.com
ARG BASE_IMAGE=ubi8/ubi
ARG BASE_TAG=latest

#global argument for tomcat
ARG TOMCAT_VERSION=9.0.106
ARG JAVA_HOME=/usr/lib/jvm/zulu21
ARG MAVEN_HOME=/opt/apache-maven-3.8.5

#setting up the tomcat builder for later below. this is for env var expansion.
FROM quay.io/semoss/tomcat-builder:${TOMCAT_VERSION} AS tomcat_builder

# FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS base
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS mavenpuller

# Define environment variables in this stage
ARG TOMCAT_VERSION
ARG JAVA_HOME
ARG MAVEN_HOME
ARG SEMOSS_VERSION
ENV JAVA_HOME=${JAVA_HOME}
ENV TOMCAT_HOME=/opt/apache-tomcat-${TOMCAT_VERSION}
ENV MAVEN_HOME=${MAVEN_HOME}
ENV PATH=$PATH:$MAVEN_HOME/bin:$TOMCAT_HOME/bin:$JAVA_HOME/bin
ENV SEMOSS_VERSION=${SEMOSS_VERSION}

# Get tomcat, maven and java from another image called tomcat-builder
COPY --from=tomcat_builder /opt /opt
COPY --from=tomcat_builder /usr/lib/jvm/zulu21 /usr/lib/jvm/zulu21

RUN yum update -y \
	&& yum install -y git curl unzip lsof procps-ng \
	&& mkdir /opt/semosshome \
	&& cd /opt && git clone https://github.com/SEMOSS/semoss-artifacts \
	&& chmod 777 /opt/semoss-artifacts/artifacts/scripts/*.sh \
	&& /opt/semoss-artifacts/artifacts/scripts/update_latest_dev.sh \
	&& chmod 777 /opt/semosshome/config/Chromedriver/* \
    && sed -i "s/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar,/g" $TOMCAT_HOME/conf/catalina.properties;

# Create a group 'root' with GID 0 if it doesn't exist (it should by default)
RUN groupadd -g 0 root || true
RUN useradd -u 1001 -r -g 0 -d /opt/semosshome -s /bin/bash \
    -c "Default Application User" default && \
    chown -R 1001:0 /opt/semosshome

RUN mkdir /opt/chroot

RUN chown -R 1001:0 /opt

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS final

LABEL maintainer="semoss@semoss.org"

# From JAVA/tomcat
ARG TOMCAT_VERSION
ARG JAVA_HOME
ARG MAVEN_HOME
ENV JAVA_HOME=${JAVA_HOME}
ENV TOMCAT_VERSION=${TOMCAT_VERSION}
ENV TOMCAT_HOME=/opt/apache-tomcat-${TOMCAT_VERSION}
ENV VIRTUAL_ENV="/usr/lib/python/semossvenv"
ENV PATH=$VIRTUAL_ENV/bin:$PATH:$MAVEN_HOME/bin:$TOMCAT_HOME/bin:$JAVA_HOME/bin:/opt/semoss-artifacts/artifacts/scripts
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

COPY --from=tomcat_builder /usr/lib/jvm/zulu21 /usr/lib/jvm/zulu21

RUN	yum update -y \
	&& yum install -y git curl unzip lsof vim nano procps-ng \
	&& curl https://rclone.org/install.sh | bash \
	&& chmod 755 /usr/bin/rclone

## TODO - Chrome installation for UBI8 would be different.
# RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
# 	&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list \
# 	&& yum update \
# 	&& yum install -y google-chrome-stable bash


COPY --from=mavenpuller --chown=1001:0 /opt /opt
COPY --from=quay.io/semoss/python-builder:3.12-cpu  /usr/lib/python /usr/lib/python


#LOCALE
RUN yum update -y \
	&& yum install -y glibc-langpack-en \
	&& localedef -i en_US -f UTF-8 en_US.UTF-8 \
	&& echo "LANG=en_US.UTF-8" > /etc/locale.conf

RUN yum install -y debootstrap fakechroot fakeroot

# Create a group 'root' with GID 0 if it doesn't exist (it should by default)
RUN groupadd -g 0 root || true
RUN useradd -u 1001 -r -g 0 -d /opt/semosshome -s /bin/bash \
    -c "Default Application User" default && \
    chown -R 1001:0 /opt/semosshome

USER 1001

WORKDIR /opt/semoss-artifacts/artifacts/scripts
CMD ["bash", "-c", "exec $TOMCAT_HOME/bin/start.sh" ]
