# Base image arguments
ARG BASE_REGISTRY=docker.io
ARG BASE_IMAGE=ubuntu
ARG BASE_TAG=22.04
ARG TOMCAT_VERSION
ARG PYTHON_VERSION

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS base
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} AS mavenpuller

ARG JAVA_HOME=/usr/lib/jvm/zulu8
ENV JAVA_HOME=${JAVA_HOME}
# From JAVA/tomcat
ARG JAVA_HOME=/usr/lib/jvm/zulu8
ENV JAVA_HOME=${JAVA_HOME}

# Passing in PYTHON_VERSION and TOMCAT_VERSION dynamically through the build pipeline
#ARG TOMCAT_VERSION=9.0.102
ENV PYTHON_VERSION=${PYTHON_VERSION}
ENV TOMCAT_VERSION=${TOMCAT_VERSION}

ARG TOMCAT_HOME=/opt/apache-tomcat-${TOMCAT_VERSION}
ENV TOMCAT_HOME=${TOMCAT_HOME}
ARG MAVEN_HOME=/opt/apache-maven-3.8.5
ENV MAVEN_HOME=${MAVEN_HOME}
ENV PATH=$PATH:$MAVEN_HOME/bin:$TOMCAT_HOME/bin:$JAVA_HOME/bin

FROM quay.io/semoss/tomcat-builder:${TOMCAT_VERSION} as tomcat_base
FROM tomcat_base as tomcat_builder

# Get tomcat, maven and java from another image called tomcat-builder
COPY --from=tomcat_base /opt /opt
COPY --from=tomcat_base /usr/lib/jvm/zulu8 /usr/lib/jvm/zulu8
COPY --from=tomcat_base /opt/apache-maven-3.8.5/bin /opt/apache-maven-3.8.5/bin

# Get python from python-builder
#COPY --from=quay.io/semoss/python-builder:${PYTHON_VERSION} /usr/lib/python /usr/lib/python
#COPY --from=quay.io/semoss/python-builder:${PYTHON_VERSION} /usr/lib/uv/ /usr/lib/uv/

RUN apt-get update -y \
    # added git curl
	&& apt-get install -y git curl unzip lsof \
	&& mkdir /opt/semosshome \
	&& cd /opt && git clone https://github.com/SEMOSS/semoss-artifacts \
	&& chmod 777 /opt/semoss-artifacts/artifacts/scripts/*.sh \
	&& /opt/semoss-artifacts/artifacts/scripts/update_latest_dev.sh \
	&& chmod 777 /opt/semosshome/config/Chromedriver/* \
	&& sed -i "s/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar,/g" $TOMCAT_HOME/conf/catalina.properties;


RUN useradd -u 1001 -r -g 0 -d ${HOME} -s /bin/bash         \
-c "Default Application User" default &&                \
chown -R 1001:0 ${HOME}

RUN mkdir /opt/chroot

RUN chown -R 1001:0 /opt

FROM base AS intermediate

LABEL maintainer="semoss@semoss.org"

# From JAVA/tomcat
ARG JAVA_HOME=/usr/lib/jvm/zulu8
ENV JAVA_HOME=${JAVA_HOME}

ARG TOMCAT_HOME=/opt/apache-tomcat-${TOMCAT_VERSION}   
ENV TOMCAT_HOME=${TOMCAT_HOME}

COPY --from=tomcat_base /opt /opt
COPY --from=tomcat_base /usr/lib/jvm/zulu8 /usr/lib/jvm/zulu8

# from original semoss dockerfile
ARG LD_LIBRARY_PATH

ENV PATH=$PATH:/opt/semoss-artifacts/artifacts/scripts
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH


RUN	apt update -y \
    # added git
	&& apt-get install -y git curl unzip lsof \
	&& curl https://rclone.org/install.sh | bash \
	&& chmod 755 /usr/bin/rclone
#	&& mkdir /opt/semosshome \
#	&& mkdir $TOMCAT_HOME/webapps/Monolith \
#	&& mkdir $TOMCAT_HOME/webapps/SemossWeb \
#	&& cp $JAVA_HOME/lib/tools.jar $TOMCAT_HOME/lib \
#	&& sed -i "s/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=/tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar,/g" $TOMCAT_HOME/conf/catalina.properties;

## TODO - couldnt get the following to work
# RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
# 	&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list \
# 	&& apt-get update \
# 	&& apt-get install -y google-chrome-stable bash


RUN apt-get update -y \
	&& apt-get install -y curl lsof \
	&& cd /opt && git clone https://github.com/SEMOSS/semoss-artifacts \
	&& chmod 777 /opt/semoss-artifacts/artifacts/scripts/*.sh


#COPY --from=mavenpuller /opt/semosshome /opt/semosshome
#COPY --from=mavenpuller $TOMCAT_HOME/webapps/Monolith $TOMCAT_HOME/webapps/Monolith
#COPY --from=mavenpuller $TOMCAT_HOME/webapps/SemossWeb $TOMCAT_HOME/webapps/SemossWeb
#COPY --from=mavenpuller /opt/semoss-artifacts/ver.txt /opt/semoss-artifacts/ver.txt

COPY --from=mavenpuller  --chown=1001:0 /opt /opt
#COPY --from=quay.io/semoss/python-builder:${PYTHON_VERSION}-cpu  /usr/lib/python /usr/lib/python

FROM quay.io/semoss/python-builder:${PYTHON_VERSION}-cpu as python_base
FROM python_base as python_builder
COPY --from=python_base /usr/lib/python /usr/lib/python

# FROM scratch AS final

# COPY --from=intermediate  / /

# ARG JAVA_HOME
# ARG TOMCAT_HOME
# ARG R_HOME
# ARG R_LIBS_SITE
# ARG RSTUDIO_PANDOC

# ENV JAVA_HOME=$JAVA_HOME
# ENV TOMCAT_HOME=$TOMCAT_HOME
# ENV R_HOME=$R_HOME
# ENV R_LIBS_SITE=$R_LIBS_SITE
# ENV RSTUDIO_PANDOC=$RSTUDIO_PANDOC

#LOCALE
RUN apt-get update \
	&& apt-get install -y locales \
	&& locale-gen en_US.UTF-8 \
	&& dpkg-reconfigure --frontend=noninteractive locales \
	&& locale -a

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8


RUN apt install -y debootstrap fakechroot fakeroot

RUN useradd -u 1001 -r -g 0 -d ${HOME} -s /bin/bash         \
	-c "Default Application User" default &&                \
	chown -R 1001:0 ${HOME}

USER 1001

ENV VIRTUAL_ENV="/usr/lib/python/semossvenv"
# ENV PYTHONHOME=$VIRTUAL_ENV
ENV PATH=$VIRTUAL_ENV/bin:$PATH:/opt/apache-maven-3.8.5/bin:$TOMCAT_HOME/bin:$JAVA_HOME/bin::/opt/semoss-artifacts/artifacts/scripts
WORKDIR /opt/semoss-artifacts/artifacts/scripts
CMD ["bash", "-c", "exec $TOMCAT_HOME/bin/start.sh" ]
