/* This file was generated by SableCC (http://www.sablecc.org/). */

package prerna.sablecc.lexer;

import java.io.*;
import prerna.sablecc.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCol(line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComparator(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqual(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColadd(line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TApi(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMath(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColjoin(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColprefix(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTablePrefix(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TValprefix(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColremove(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColfilter(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColunfilter(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColimport(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColset(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColpivot(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColfocus(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColalias(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColrename(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColsplit(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCollink(line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShowHide(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBracket(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBracket(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLCurlBracket(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRCurlBracket(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGroup(line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpace(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNewline(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TJava(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPython(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProc(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThis(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNull(line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImportType(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRelType(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDataimporttoken(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDataremovetoken(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDataopentoken(line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLiteral(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THelpToken(line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCodeblock(text, line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWord(text, line, pos); }
    Token new57(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelviz(text, line, pos); }
    Token new58(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelclone(text, line, pos); }
    Token new59(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelclose(text, line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDataframe(line, pos); }
    Token new61(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFileText(text, line, pos); }
    Token new62(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelcommentremove(text, line, pos); }
    Token new63(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelcommentedit(text, line, pos); }
    Token new64(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelcommentadd(text, line, pos); }
    Token new65(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanellookandfeel(text, line, pos); }
    Token new66(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPaneltools(text, line, pos); }
    Token new67(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPanelconfig(text, line, pos); }
    Token new68(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOutputToken(text, line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUserinput(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TJoin(line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDatatypeToken(line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {33, 33, 4}, {34, 34, 5}, {37, 37, 6}, {39, 39, 7}, {40, 40, 8}, {41, 41, 9}, {42, 42, 10}, {43, 43, 11}, {44, 44, 12}, {45, 45, 13}, {46, 46, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 90, 22}, {91, 91, 23}, {92, 92, 24}, {93, 93, 25}, {95, 95, 26}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 30}, {101, 101, 28}, {102, 102, 31}, {103, 103, 32}, {104, 104, 28}, {105, 105, 33}, {106, 106, 34}, {107, 107, 28}, {108, 108, 35}, {109, 109, 36}, {110, 110, 37}, {111, 111, 38}, {112, 112, 39}, {113, 113, 28}, {114, 114, 40}, {115, 115, 41}, {116, 116, 42}, {117, 117, 43}, {118, 118, 44}, {119, 122, 28}, {123, 123, 45}, {125, 125, 46}, },
            {{10, 10, 1}, {13, 13, 47}, {32, 32, 48}, },
            {{10, 32, -2}, },
            {{10, 32, -2}, },
            {{61, 61, 49}, },
            {{0, 33, 50}, {35, 38, 50}, {40, 65535, 50}, },
            {},
            {{0, 65535, -7}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 16}, {65, 90, 22}, {95, 95, 26}, {97, 122, 28}, },
            {},
            {},
            {{61, 61, 51}, {99, 99, 52}, {115, 115, 53}, },
            {},
            {{61, 61, 54}, },
            {{48, 57, 55}, {65, 122, -18}, },
            {},
            {{110, 110, 56}, {114, 114, 57}, },
            {},
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 111, 28}, {112, 112, 58}, {113, 122, 28}, },
            {{48, 122, -24}, },
            {{48, 57, 55}, {58, 58, 59}, {65, 95, -18}, {97, 97, 60}, {98, 110, 28}, {111, 111, 61}, {112, 113, 28}, {114, 114, 62}, {115, 122, 28}, },
            {{48, 95, -24}, {97, 97, 63}, {98, 122, 28}, },
            {{48, 95, -24}, {97, 107, 28}, {108, 108, 64}, {109, 122, 28}, },
            {{48, 95, -24}, {97, 113, 28}, {114, 114, 65}, {115, 122, 28}, },
            {{48, 95, -24}, {97, 109, 28}, {110, 110, 66}, {111, 122, 28}, },
            {{48, 57, 55}, {58, 58, 67}, {65, 122, -18}, },
            {{48, 95, -24}, {97, 100, 28}, {101, 101, 68}, {102, 104, 28}, {105, 105, 69}, {106, 122, 28}, },
            {{46, 46, 70}, {48, 57, 55}, {58, 58, 71}, {65, 95, -18}, {97, 97, 72}, {98, 122, 28}, },
            {{48, 95, -24}, {97, 116, 28}, {117, 117, 73}, {118, 122, 28}, },
            {{48, 95, -24}, {97, 101, 28}, {102, 102, 74}, {103, 109, 28}, {110, 110, 75}, {111, 116, 28}, {117, 117, 76}, {118, 122, 28}, },
            {{48, 57, 55}, {58, 58, 77}, {65, 95, -18}, {97, 97, 78}, {98, 122, 28}, },
            {{48, 95, -24}, {97, 104, 28}, {105, 105, 79}, {106, 122, 28}, },
            {{48, 100, -37}, {101, 101, 80}, {102, 122, 28}, },
            {{48, 57, 55}, {58, 58, 81}, {65, 95, -18}, {97, 103, 28}, {104, 104, 82}, {105, 113, 28}, {114, 114, 83}, {115, 122, 28}, },
            {{48, 95, -24}, {97, 114, 28}, {115, 115, 84}, {116, 122, 28}, },
            {{48, 57, 55}, {58, 58, 85}, {65, 122, -18}, },
            {},
            {},
            {{10, 32, -3}, },
            {{10, 32, -3}, },
            {},
            {{0, 33, 50}, {34, 34, 86}, {35, 38, 50}, {39, 39, 87}, {40, 65535, 50}, },
            {},
            {{111, 111, 88}, },
            {{116, 116, 89}, },
            {},
            {{48, 122, -24}, },
            {},
            {{92, 92, 90}, },
            {{48, 104, -42}, {105, 105, 91}, {106, 122, 28}, },
            {},
            {{48, 107, -33}, {108, 108, 92}, {109, 122, 28}, },
            {{48, 107, -33}, {108, 108, 93}, {109, 122, 28}, },
            {{48, 95, -24}, {97, 110, 28}, {111, 111, 94}, {112, 122, 28}, },
            {{48, 95, -24}, {97, 115, 28}, {116, 116, 95}, {117, 122, 28}, },
            {{48, 95, -24}, {97, 97, 96}, {98, 122, 28}, },
            {{48, 110, -64}, {111, 111, 97}, {112, 122, 28}, },
            {{48, 101, -40}, {102, 102, 98}, {103, 109, 28}, {110, 110, 99}, {111, 122, 28}, },
            {},
            {{48, 101, -40}, {102, 102, 100}, {103, 122, 28}, },
            {{48, 95, -24}, {97, 106, 28}, {107, 107, 101}, {108, 109, 28}, {110, 110, 102}, {111, 122, 28}, },
            {},
            {},
            {{48, 115, -65}, {116, 116, 103}, {117, 122, 28}, },
            {{48, 107, -33}, {108, 108, 104}, {109, 122, 28}, },
            {{48, 101, -40}, {102, 102, 105}, {103, 122, 28}, },
            {{48, 122, -24}, },
            {{48, 115, -65}, {116, 116, 106}, {117, 122, 28}, },
            {},
            {{48, 109, -35}, {110, 110, 107}, {111, 122, 28}, },
            {{48, 95, -24}, {97, 102, 28}, {103, 103, 108}, {104, 122, 28}, },
            {{48, 107, -33}, {108, 108, 109}, {109, 122, 28}, },
            {},
            {{48, 104, -42}, {105, 105, 110}, {106, 122, 28}, },
            {{48, 100, -37}, {101, 101, 111}, {102, 122, 28}, },
            {{48, 100, -37}, {101, 101, 112}, {102, 122, 28}, },
            {},
            {},
            {},
            {{100, 100, 113}, },
            {{97, 97, 114}, },
            {{110, 110, 56}, },
            {{48, 57, 55}, {58, 58, 115}, {65, 122, -18}, },
            {{48, 107, -33}, {108, 108, 116}, {109, 122, 28}, },
            {{46, 46, 117}, {48, 122, -24}, },
            {{48, 114, -45}, {115, 115, 118}, {116, 122, 28}, },
            {{48, 95, -24}, {97, 97, 119}, {98, 122, 28}, },
            {{48, 115, -65}, {116, 116, 120}, {117, 122, 28}, },
            {{48, 116, -39}, {117, 117, 121}, {118, 122, 28}, },
            {{48, 110, -64}, {111, 111, 122}, {112, 122, 28}, },
            {{48, 100, -37}, {101, 101, 123}, {102, 122, 28}, },
            {{48, 115, -65}, {116, 116, 124}, {117, 122, 28}, },
            {{48, 100, -37}, {101, 101, 125}, {102, 122, 28}, },
            {{48, 106, -71}, {107, 107, 126}, {108, 122, 28}, },
            {{48, 95, -24}, {97, 103, 28}, {104, 104, 127}, {105, 122, 28}, },
            {{48, 107, -33}, {108, 108, 128}, {109, 122, 28}, },
            {{48, 122, -24}, },
            {{48, 100, -37}, {101, 101, 129}, {102, 122, 28}, },
            {{48, 100, -37}, {101, 101, 130}, {102, 122, 28}, },
            {{48, 103, -105}, {104, 104, 131}, {105, 122, 28}, },
            {{48, 101, -40}, {102, 102, 132}, {103, 122, 28}, },
            {{48, 114, -45}, {115, 115, 133}, {116, 122, 28}, },
            {{48, 100, -37}, {101, 101, 134}, {102, 122, 28}, },
            {{48, 113, -34}, {114, 114, 135}, {115, 122, 28}, },
            {{101, 101, 136}, },
            {{114, 114, 137}, },
            {},
            {{48, 57, 55}, {58, 58, 138}, {65, 122, -18}, },
            {{97, 97, 139}, {102, 102, 140}, {105, 105, 141}, {106, 106, 142}, {112, 112, 143}, {114, 114, 144}, {115, 115, 145}, {117, 117, 146}, },
            {{48, 114, -45}, {115, 115, 147}, {116, 122, 28}, },
            {{46, 46, 148}, {48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 111, -29}, {112, 112, 149}, {113, 122, 28}, },
            {{46, 46, 150}, {48, 122, -24}, },
            {{48, 113, -34}, {114, 114, 151}, {115, 122, 28}, },
            {{46, 46, 152}, {48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 57, 55}, {58, 58, 153}, {65, 122, -18}, },
            {{46, 46, 154}, {48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 113, -34}, {114, 114, 155}, {115, 122, 28}, },
            {{48, 107, -33}, {108, 108, 156}, {109, 122, 28}, },
            {{48, 115, -65}, {116, 116, 157}, {117, 122, 28}, },
            {{46, 46, 158}, {48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{46, 46, 159}, {48, 122, -24}, },
            {{62, 62, 160}, },
            {{116, 116, 161}, },
            {},
            {{100, 100, 162}, {108, 108, 163}, },
            {{105, 105, 164}, {111, 111, 165}, },
            {{109, 109, 166}, },
            {{111, 111, 167}, },
            {{105, 105, 168}, },
            {{101, 101, 169}, },
            {{101, 101, 170}, {112, 112, 171}, },
            {{110, 110, 172}, },
            {{46, 46, 173}, {48, 122, -24}, },
            {{102, 102, 174}, {105, 105, 175}, {106, 106, 176}, {111, 111, 177}, {114, 114, 178}, {116, 116, 179}, },
            {{48, 57, 55}, {58, 58, 180}, {65, 122, -18}, },
            {{104, 104, 181}, },
            {{46, 46, 182}, {48, 122, -24}, },
            {{111, 111, 183}, },
            {},
            {},
            {{46, 46, 184}, {48, 122, -24}, },
            {{46, 46, 185}, {48, 90, -24}, {91, 91, 186}, {95, 122, -18}, },
            {{46, 46, 187}, {48, 122, -24}, },
            {{106, 106, 188}, },
            {{105, 105, 189}, },
            {{0, 59, 190}, {60, 60, 191}, {61, 65535, 190}, },
            {{73, 73, 192}, },
            {{100, 100, 193}, },
            {{105, 105, 194}, },
            {{108, 108, 195}, },
            {{99, 99, 196}, },
            {{112, 112, 197}, },
            {{105, 105, 198}, },
            {{118, 118, 199}, },
            {{109, 109, 200}, {110, 110, 201}, },
            {{116, 116, 202}, },
            {{108, 108, 203}, },
            {{102, 102, 204}, },
            {{106, 106, 205}, },
            {{114, 114, 206}, },
            {{109, 109, 207}, },
            {{111, 111, 208}, },
            {{112, 112, 209}, },
            {{101, 101, 210}, },
            {{121, 121, 211}, },
            {},
            {{101, 101, 212}, },
            {{106, 106, 213}, },
            {{117, 117, 214}, },
            {{106, 106, 215}, },
            {{99, 99, 216}, {108, 108, 217}, {116, 116, 218}, {118, 118, 219}, },
            {{48, 57, 220}, },
            {{111, 111, 221}, },
            {{111, 111, 222}, },
            {{110, 110, 223}, },
            {{0, 65535, -162}, },
            {{0, 60, -162}, {61, 98, 190}, {99, 99, 224}, {100, 65535, 190}, },
            {{110, 110, 225}, },
            {},
            {{97, 97, 226}, },
            {{116, 116, 227}, },
            {{117, 117, 228}, },
            {{111, 111, 229}, },
            {{110, 110, 230}, },
            {{111, 111, 231}, },
            {{111, 111, 232}, },
            {{97, 97, 233}, },
            {},
            {{105, 105, 234}, },
            {{105, 105, 235}, },
            {{111, 111, 236}, },
            {{97, 97, 237}, },
            {{112, 112, 238}, },
            {{105, 105, 239}, },
            {{101, 101, 240}, },
            {{109, 109, 241}, },
            {{112, 112, 242}, },
            {{108, 108, 243}, },
            {{111, 111, 244}, },
            {{116, 116, 245}, },
            {{111, 111, 246}, },
            {{108, 108, 247}, {111, 111, 248}, {114, 114, 249}, },
            {{111, 111, 250}, },
            {{111, 111, 251}, },
            {{105, 105, 252}, },
            {{93, 93, 253}, },
            {{117, 117, 254}, },
            {{105, 105, 255}, },
            {{112, 112, 256}, },
            {{0, 60, -162}, {61, 110, 190}, {111, 111, 257}, {112, 65535, 190}, },
            {{112, 112, 258}, },
            {{115, 115, 259}, },
            {{101, 101, 260}, },
            {{115, 115, 261}, },
            {{114, 114, 262}, },
            {},
            {{116, 116, 263}, },
            {{118, 118, 264}, },
            {{109, 109, 265}, },
            {{116, 116, 266}, },
            {{108, 108, 267}, },
            {{105, 105, 268}, },
            {{109, 109, 269}, },
            {{111, 111, 270}, },
            {{110, 110, 271}, },
            {{110, 110, 272}, },
            {{111, 111, 273}, },
            {{101, 101, 274}, },
            {{112, 112, 275}, },
            {{105, 105, 276}, },
            {{101, 101, 277}, },
            {{105, 105, 278}, },
            {{111, 111, 279}, },
            {{109, 109, 280}, {110, 110, 281}, },
            {{101, 101, 282}, },
            {{111, 111, 283}, },
            {{111, 111, 284}, },
            {{122, 122, 285}, },
            {{46, 46, 185}, },
            {{116, 116, 286}, },
            {{110, 110, 287}, },
            {{117, 117, 288}, },
            {{0, 60, -162}, {61, 99, 190}, {100, 100, 289}, {101, 65535, 190}, },
            {{117, 117, 290}, },
            {},
            {{114, 114, 291}, },
            {},
            {{116, 116, 292}, },
            {},
            {{101, 101, 293}, },
            {{101, 101, 294}, },
            {},
            {{116, 116, 295}, },
            {{110, 110, 296}, },
            {{101, 101, 297}, },
            {{114, 114, 298}, },
            {},
            {},
            {{118, 118, 299}, },
            {},
            {},
            {{110, 110, 300}, },
            {{114, 114, 301}, },
            {{110, 110, 302}, },
            {{110, 110, 303}, {115, 115, 304}, },
            {{109, 109, 305}, },
            {{102, 102, 306}, },
            {{97, 97, 307}, },
            {{107, 107, 308}, },
            {{108, 108, 309}, },
            {},
            {{101, 101, 310}, },
            {},
            {{116, 116, 311}, },
            {{0, 60, -162}, {61, 100, 190}, {101, 101, 312}, {102, 65535, 190}, },
            {{116, 116, 313}, },
            {},
            {},
            {},
            {},
            {{101, 101, 314}, },
            {},
            {},
            {{116, 116, 315}, },
            {{101, 101, 316}, },
            {},
            {{46, 46, 317}, },
            {},
            {{101, 101, 318}, },
            {{101, 101, 319}, },
            {{101, 101, 320}, },
            {{105, 105, 321}, },
            {{116, 116, 322}, },
            {{97, 97, 323}, },
            {{115, 115, 324}, },
            {{114, 114, 325}, },
            {},
            {{0, 60, -162}, {61, 61, 190}, {62, 62, 326}, {63, 65535, 190}, },
            {{62, 62, 327}, },
            {{114, 114, 328}, },
            {},
            {},
            {{106, 106, 329}, },
            {},
            {},
            {{110, 110, 330}, },
            {{103, 103, 331}, },
            {{101, 101, 332}, },
            {{110, 110, 333}, },
            {},
            {{46, 46, 334}, },
            {{0, 65535, -162}, },
            {{0, 59, 335}, {60, 60, 336}, {61, 65535, 335}, },
            {},
            {{111, 111, 337}, },
            {{116, 116, 338}, },
            {},
            {},
            {{100, 100, 339}, },
            {{106, 106, 340}, },
            {{0, 65535, -329}, },
            {{0, 60, -329}, {61, 100, 335}, {101, 101, 341}, {102, 65535, 335}, },
            {{105, 105, 342}, },
            {{46, 46, 343}, {91, 91, 344}, },
            {{102, 102, 345}, },
            {{111, 111, 346}, },
            {{0, 60, -329}, {61, 109, 335}, {110, 110, 347}, {111, 65535, 335}, },
            {{110, 110, 348}, },
            {{97, 97, 349}, {101, 101, 350}, {114, 114, 351}, },
            {{48, 57, 352}, },
            {{101, 101, 353}, },
            {{105, 105, 354}, },
            {{0, 60, -329}, {61, 99, 335}, {100, 100, 355}, {101, 65535, 335}, },
            {},
            {{100, 100, 356}, },
            {{100, 100, 357}, },
            {{101, 101, 358}, },
            {{93, 93, 359}, },
            {{101, 101, 360}, },
            {{110, 110, 361}, },
            {{0, 60, -329}, {61, 72, 335}, {73, 73, 362}, {74, 65535, 335}, },
            {{100, 100, 363}, },
            {{105, 105, 364}, },
            {{109, 109, 365}, },
            {{46, 46, 343}, },
            {{108, 108, 366}, },
            {},
            {{0, 109, -343}, {110, 110, 367}, {111, 65535, 335}, },
            {},
            {{116, 116, 368}, },
            {{111, 111, 369}, },
            {},
            {{0, 60, -329}, {61, 111, 335}, {112, 112, 370}, {113, 65535, 335}, },
            {},
            {{118, 118, 371}, },
            {{0, 60, -329}, {61, 116, 335}, {117, 117, 372}, {118, 65535, 335}, },
            {{101, 101, 373}, },
            {{0, 60, -329}, {61, 115, 335}, {116, 116, 374}, {117, 65535, 335}, },
            {},
            {{0, 60, -329}, {61, 61, 335}, {62, 62, 375}, {63, 65535, 335}, },
            {{0, 65535, -329}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {1, 40, 40, 40, -1, -1, 32, -1, 33, 34, 7, 5, 8, 6, 2, 9, 0, 4, 3, 11, 12, 11, 1, 35, -1, 36, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 37, 38, 40, 40, 11, -1, 11, -1, -1, 11, 1, 42, -1, 1, 17, 1, 1, 1, 1, 1, 1, 1, 43, 1, 1, 15, 45, 1, 1, 1, 1, 1, 44, 1, 1, 1, 18, 1, 1, 1, 19, 56, 56, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 14, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 30, 15, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 39, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 13, -1, -1, -1, -1, -1, -1, -1, -1, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 27, -1, 26, -1, 25, -1, -1, 29, -1, -1, -1, -1, 70, 52, -1, 71, 54, -1, -1, -1, -1, -1, -1, -1, -1, -1, 57, -1, 49, -1, -1, -1, 21, 23, 20, 28, -1, 49, 60, -1, -1, 49, -1, 49, -1, -1, -1, -1, -1, -1, -1, -1, 69, -1, -1, -1, 50, 51, -1, 58, 59, -1, -1, -1, -1, 66, -1, 55, -1, 22, -1, -1, 67, 68, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 49, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 49, -1, 64, -1, -1, 65, -1, 63, -1, -1, -1, -1, 62, -1, 61, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
