name: Auto Comment on PR

on:
  pull_request:
    types: [opened]

jobs:
  add-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Add describe comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @CodiumAI-Agent /describe

      - name: Wait for 45 seconds
        run: sleep 45

      - name: Add review comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @CodiumAI-Agent /review

      - name: Wait for 45 seconds
        run: sleep 45

      - name: Add improve comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @CodiumAI-Agent /improve
